---
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Debian Installation
  include: ubuntu.yml
  when: ansible_os_family == 'Debian'

- name: RedHat Installation
  include: redhat.yml
  when: ansible_os_family == 'RedHat'


# setuo docker

- name: Run dockerized bitcoind
  command: "docker run --name bitcoind_{{ network_id }} -d -v {{ datadir }}:/data -p 8333:8333 -p 9735:9735 dougvk/bitcoind:latest"




# bitcoind setup.
- name: Copy bitwise bitcoin configuration in place.
  template:
    src: bitcoin.conf.j2
    dest: /etc/bitcoind/bitcoin.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - reload bitcoind
