---
- name: RedHat | Enable bitcoin repo.
  template:
    src: nginx.repo.j2
    dest: /etc/yum.repos.d/bitcoin.repo
    owner: root
    group: root
    mode: 0644

- name: RedHat | Ensure nginx is installed.
  yum: pkg=bitcoind state=installed enablerepo=bitcoin
